# Load the base image
FROM python:3.14.5-slim-trixie

# Numerics research group
LABEL maintainer="numerics@iag.uni-stuttgart.de"

# Setup uv environment variables
# > Avoid interactive prompts and reduce extra files
ENV DEBIAN_FRONTEND=noninteractive \
    PATH="/.local/bin:$PATH"       \
    UV_LINK_MODE=copy

# Set architecture argument
ARG ARCH

# Setup required packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      curl                         \
      git                          \
      git-lfs                      \
      libglu1-mesa                 \
      libglut3.12                  \
      libgomp1                     \
      libpng16-16t64               \
      libxcursor1                  \
      libxft2                      \
      libxinerama1              && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean               && \
    rm -rf                         \
      /usr/share/doc/*             \
      /usr/share/man/*             \
      /var/log/*                   \
      /tmp/*

# Setup uv package manager
RUN mkdir -p /.local/bin && \
    curl -fsSL -o /tmp/uv.tar.gz   \
      https://github.com/astral-sh/uv/releases/download/0.10.2/uv-x86_64-unknown-linux-gnu.tar.gz && \
    tar -xzf /tmp/uv.tar.gz -C /.local/bin --strip-components=1 && \
    rm /tmp/uv.tar.gz
