# Load the base image
FROM python:3.14.5-alpine3.23

# Numerics research group
LABEL maintainer="numerics@iag.uni-stuttgart.de"

# Setup uv environment variables
# > Avoid interactive prompts and reduce extra files
ENV PATH="/.local/bin:$PATH"       \
    UV_LINK_MODE=copy

# Set architecture argument
ARG ARCH

# Setup required packages
RUN apk update && \
    apk add --no-cache             \
      curl                         \
      fontconfig                   \
      gcompat                      \
      git                          \
      git-lfs                      \
      glu                          \
      libstdc++                    \
      libgcc                       \
      libgomp                      \
      libpng                       \
      libxcb                       \
      libxext                      \
      libxfixes                    \
      libxft                       \
      libxrender                && \
    rm /var/cache/apk/*         && \
    rm -rf                         \
      /usr/share/doc/*             \
      /usr/share/man/*             \
      /var/log/*                   \
      /tmp/*

# Setup uv package manager
RUN mkdir -p /.local/bin && \
    curl -fsSL -o /tmp/uv.tar.gz   \
      https://github.com/astral-sh/uv/releases/download/0.10.2/uv-x86_64-unknown-linux-musl.tar.gz && \
    tar -xzf /tmp/uv.tar.gz -C /.local/bin --strip-components=1 && \
    rm /tmp/uv.tar.gz
