# Load the base image
FROM fedora:42

# Numerics research group
LABEL maintainer="numerics@iag.uni-stuttgart.de"

# Disable weak dependencies
RUN echo 'install_weak_deps=False' >> /etc/dnf/dnf.conf

# Setup required packages
RUN dnf makecache && \
    dnf update -y && \
    dnf install -y mesa-libGLU freeglut libXcursor libXft libXinerama && \
    dnf install -y git-core cmake gcc-c++ gcc-gfortran mpich-devel zlib-ng-devel libpng openblas-devel hdf5-mpich-devel && \
    dnf install -y python3 uv && \
    dnf autoremove            && \
    dnf clean all             && \
    rm -rf /var/log/dnf5.*

# Set architecture argument
ARG ARCH

# Setup uv
ENV UV_LINK_MODE=copy

# Setup standard paths
ENV LD_LIBRARY_PATH="/usr/lib64"           \
    MANPATH="/usr/share/man"               \
    PKG_CONFIG_PATH="/usr/lib64/pkgconfig"

# Setup MPI
# RUN source /etc/profile && module load mpi
# > Each RUN command in a Dockerfile starts a new shell process, thus Docker
# > does not persist the shell state, including environment modifications
# > such as module load, across RUN commands.
ENV MPI_BIN=/usr/lib64/mpich/bin           \
    MPI_SYSCONFIG=/etc/mpich-${ARCH}       \
    MPI_FORTRAN_MOD_DIR=/usr/lib64/gfortran/modules/mpich          \
    MPI_INCLUDE=/usr/include/mpich-${ARCH} \
    MPI_LIB=/usr/lib64/mpich/lib           \
    MPI_MAN=/usr/share/man/mpich-${ARCH}   \
    MPI_PYTHON3_SITEARCH=/usr/lib64/python3.13/site-packages/mpich \
    MPI_COMPILER=mpich-${ARCH}             \
    MPI_SUFFIX=_mpich                      \
    MPI_HOME=/usr/lib64/mpich              \
    PATH="/usr/lib64/mpich/bin:${PATH}"    \
    LD_LIBRARY_PATH="/usr/lib64/mpich/lib:${LD_LIBRARY_PATH}"      \
    MANPATH="/usr/share/man/mpich-${ARCH}:${MANPATH}"              \
    PKG_CONFIG_PATH="/usr/lib64/mpich/lib/pkgconfig:${PKG_CONFIG_PATH}"

# Setup FLEXI
# ADD --keep-git-dir=true "https://github.com/flexi-framework/flexi.git" /flexi
RUN git clone --branch master --single-branch --depth 1 https://github.com/flexi-framework/flexi.git /flexi.src && \
    cd /flexi.src                  && \
    cmake -B build                    \
      -DCMAKE_BUILD_TYPE=Release      \
      -DCMAKE_INSTALL_PREFIX=/flexi   \
      -DFLEXI_PERFORMANCE=ON          \
      -DFLEXI_PERFORMANCE_OPTLIFT=ON  \
      -DFLEXI_INSTRUCTION='-march=x86-64 -mtune=generic' && \
    cmake --build build            && \
    cmake --install build          && \
    cp -r  /flexi.src/tools /flexi && \
    rm -rf /flexi.src              && \
    echo '/flexi/lib' > /etc/ld.so.conf.d/flexi.conf && \
    ldconfig

WORKDIR /flexi

# Setup FLEXI with PGO
# RUN git clone --branch master --single-branch --depth 1 git@gitlab.iag.uni-stuttgart.de:flexi/codes/pgo.git /pgo
# RUN cmake -B build -DFLEXI_PERFORMANCE=ON -DFLEXI_PERFORMANCE_OPTLIFT=ON -DFLEXI_INSTRUCTION='-march=x86-64 -mtune=generic'
# WORKDIR /flexi/build
# RUN python /pgo/PGO.py
